### ISSUE TITLE
编译失败了

### ISSUE THREAD

**Issue by qiuyaofan** [Dragon-Rider/node-server#1]
ios 10.12.5版本 安装没报错，运行npm start报错

```
/node-server/node_modules/koa-static/index.js:39
    return async function serve (ctx, next) {
                 ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/qiuyaofan/Documents/lianxi/node-koa/node-server/app.js:3:21)
    at Module._compile (module.js:570:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-server-demo@1.0.0 start: `NODE_ENV=production node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-server-demo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Dragon-Rider** [comment]
@qiuyaofan 这应该是node版本不兼容依赖库导致的，我刚刚更新了代码，麻烦重新拉下代码，删除本地node_modules依赖，之后再次npm install就可以了。或者直接升级node版本，推荐使用nvm版本管理工具。

**Comment by labike** [comment]
版本koa-static@3.0.3
在源代码里是没有async的。

**Comment by Dragon-Rider** [comment]
@labike 新的 package.json 我将 koa-static 降到了3.0+版本，上午他们用的koa-static": "^4.0.0 导致会报错

**Comment by Dragon-Rider** [comment]
@qiuyaofan 如果问题解决了还请关闭这个issue，谢谢：）

**Comment by qiuyaofan** [comment]
```
npm start

> node-server-demo@1.0.0 start /Users/admin/Documents/lianxi/node-koa/node-server
> NODE_ENV=production node app.js

koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md app.js:25:6
koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md app.js:27:6
```

dev.env.config和prod.env.config 修改了端口号

`const listenPort = 6000;`

但是打开http://localhost:6000/ 返回

```
无法访问此网站

网址为 http://localhost:6000/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_UNSAFE_PORT
```

**Comment by qiuyaofan** [comment]
@Dragon-Rider

**Comment by Dragon-Rider** [comment]
@qiuyaofan 换个端口就好了（eg: 6001）, 参看下面的两个回答，6000被禁止了。
https://stackoverflow.com/questions/29297390/whats-special-about-port-6000-on-mac-os
https://stackoverflow.com/questions/4313403/why-do-browsers-block-some-ports/22622633#22622633

**Comment by qiuyaofan** [comment]
这么巧，谢谢你的耐心解答 我试试
